# Generated by Django 5.1.4 on 2025-01-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pehchan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default='2 years', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='html , css, js', max_length=200),
            preserve_default=False,
        ),
    ]
