# Generated by Django 5.1.4 on 2025-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pehchan', '0004_alter_post_description_alter_post_job_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(max_length=200),
        ),
    ]
